name: JavaScript Package

on:
  push:
    tags:
      - 'JavaScript/v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies
        run: yarn
        working-directory: platforms/javascript
      - name: Publish
        run: yarn deploy
        working-directory: platforms/javascript
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
